manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: fork
      url-base: https://github.com/pauldiloreto
  projects:
    - name: zmk
      remote: fork
      revision: main
      import: app/west.yml
  self:
    path: config
